// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS4LceX-iEJp2mzJQ-aAi1cvk8Wg-_ivM',
    appId: '1:933102826503:web:8fe50d6c8c7534962e66a2',
    messagingSenderId: '933102826503',
    projectId: 'capstone-project-ed20e',
    authDomain: 'capstone-project-ed20e.firebaseapp.com',
    storageBucket: 'capstone-project-ed20e.firebasestorage.app',
    measurementId: 'G-HX07GJ2KRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMDqYRo645Z_WXypoCHvN-vmbETHgx1GY',
    appId: '1:933102826503:android:42510998d245b33c2e66a2',
    messagingSenderId: '933102826503',
    projectId: 'capstone-project-ed20e',
    storageBucket: 'capstone-project-ed20e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9126D36bMBmDv-Br6EK9-wn-huOIJVAw',
    appId: '1:933102826503:ios:b23de0b04f6b47cc2e66a2',
    messagingSenderId: '933102826503',
    projectId: 'capstone-project-ed20e',
    storageBucket: 'capstone-project-ed20e.firebasestorage.app',
    iosBundleId: 'com.example.bogoballers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9126D36bMBmDv-Br6EK9-wn-huOIJVAw',
    appId: '1:933102826503:ios:b23de0b04f6b47cc2e66a2',
    messagingSenderId: '933102826503',
    projectId: 'capstone-project-ed20e',
    storageBucket: 'capstone-project-ed20e.firebasestorage.app',
    iosBundleId: 'com.example.bogoballers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS4LceX-iEJp2mzJQ-aAi1cvk8Wg-_ivM',
    appId: '1:933102826503:web:976e10ed819102af2e66a2',
    messagingSenderId: '933102826503',
    projectId: 'capstone-project-ed20e',
    authDomain: 'capstone-project-ed20e.firebaseapp.com',
    storageBucket: 'capstone-project-ed20e.firebasestorage.app',
    measurementId: 'G-T45F7E01KJ',
  );
}
